%%%%%%       CROW 2D LOCALIZATION SUPERFUNCTION         %%%%
%   This is the master function that localizes a crow in a 2D grid. It
%   first calibrates itself by obtaining a time correction factor from
%   Crow_2D_LocalizationPrelim, then applies the time correction to the
%   final localization function, Crow_2D_Localization. The hyperobolas
%   generated by the TDOA method utilized by the localization code, the
%   places they intersect, and the estimated location of the crow (based on
%   the mean of these intersections) are stored in matrices. 
%

clear all;
close all;
elementspacing = 6;
%Select sound files from each of four microphones
[SoundFile1,PathName] = uigetfile('C:\Users\virdi_000\Documents\MATLAB\Crows\Crow-Localization-master\*.wav','Select the first file'); 
[SoundFile2,PathName] = uigetfile('C:\Users\virdi_000\Documents\MATLAB\Crows\Crow-Localization-master\*.wav','Select the first file');
[SoundFile3,PathName] = uigetfile('C:\Users\virdi_000\Documents\MATLAB\Crows\Crow-Localization-master\*.wav','Select the first file');
[SoundFile4,PathName] = uigetfile('C:\Users\virdi_000\Documents\MATLAB\Crows\Crow-Localization-master\*.wav','Select the first file');
PreStartTime = 9; %CALIBRATION START TIME: Start time of calibration signal. 
PreEndTime = 10;   %CALIBRATION END TIME: End time of calibration signal. 
StartTime = 14;    %Start time of the sound to be localized.
EndTime = 15;      %End time of the sound to be localized. 

%Preliminary function is first used to obtain the time correction.
TimeCorrection = Crow_2D_LocalizationPrelim(SoundFile1, SoundFile2, SoundFile3, SoundFile4, PreStartTime, PreEndTime,1, true, elementspacing);
%Final localization is then used, utilizing the time correction from above,
%to deliver hyperbolas, intersections and estimated location. 
[Hyperbolas, Intersections, Location] = Crow_2D_Localization(SoundFile1, SoundFile2, SoundFile3, SoundFile4, StartTime, EndTime,1, true, TimeCorrection, elementspacing);


%% Start/End times for various calls using data from 2-9-2018
%Multi-syllable call: 169-170
%Multi-syllalbe call: 201-202
%3 syllable call: 215-216
%6 syllable call: 302-303
%5 syllable call: 335-336
%chattery noise: 364-365
%Loud single caw, little noise: 597-598
%Short, sharp caw: 618-619
%What sounds like a reply to the above: 6:19-6:20





